## NumPy

In [1]:
#Importing NumPy Library
import numpy as np

Array creation

In [9]:
my_list = [1, 2.23, 3, 'num1', 5, -60, 7, 8, 9, 10]
# standard python list above

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#np array

print('list:',my_list)
print('array:',array)

list: [1, 2.23, 3, 'num1', 5, -60, 7, 8, 9, 10]
array: [ 1  2  3  4  5  6  7  8  9 10]


In [11]:
type(array)

numpy.ndarray

In [12]:
array = np.array([1, 2, 3, 4]) 
# array is made up of numbers

print(array) # prints all the data
print(array * 2) # prints each entity in the array * 2
print(array * array) 
# prints each entity in the array by itself

# really useful when dealing with large data sets to run calculations on arrays faster and less memory than a SpreadSheet
# faster than humans = AI

[1 2 3 4]
[2 4 6 8]
[ 1  4  9 16]


***One-Dimensional and Two-Dimensional Arrays***

In [13]:
# 1 dimensional array
array1 = np.array([1, 2, 3, 4, 5])

print(array1)

[1 2 3 4 5]


In [14]:
# 2 dimensional array
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array2)

# look at how it prints a 2d array [[]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Indexing 

In [11]:
#Retrievng the seceond element from the array
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [12]:
# We can even add the elements together
arr = np.array([1, 2, 3, 4])

print(arr[0] + arr[3])


5


Slicing

In [13]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

print(array[1:5]) 
# slices data from index 1 to 4  - 0 indexed and discounts final number

[2 3 4 5]


In [14]:
array2 = np.array([1, 2, 3, 4, 5, 6, 7])

print(array2[:4])  
# slices unitl index/position 4

[1 2 3 4]


In [16]:
slice = np.array([1,2,3,4,5,6,7,8]) 
# slices from 1 to 8 in increments of 2
print(slice[1:4:2])

[2 4]


NP Zerpos

In [16]:
zeros = np.zeros(10)  # single list/vector

print (zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
zeros1 = np.zeros((4, 4)) # 4 by 4 matrix 

print(zeros1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


NP Ones

In [18]:
ones = np.ones(8)  # single list/vector

print (ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
matrix = np.ones((3, 3)) # 3 by 3 matrix 

print(matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


NP Random Array

In [20]:
random = np.random.rand(3,4) #3 rows, 4 columns

print (random)

[[0.15982422 0.10875077 0.9740928  0.46754836]
 [0.20093352 0.64237196 0.38503009 0.79980656]
 [0.77323321 0.93571017 0.02466423 0.45455593]]


Arange

In [23]:
x = np.arange(10)

print(x) # evenly spaced array 

[0 1 2 3 4 5 6 7 8 9]


In [24]:
# 3rd argument to add step
array2 = np.arange(0, 15, 2)

print(array2)

[ 0  2  4  6  8 10 12 14]


Shape & Reshape 

In [25]:
#Returns shape of array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [17]:
# 1D to 2D
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newArray = array.reshape(4, 3) 
# rows then columns when creating the matrix

print(newArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# 1D array to 3D array
array1 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])

newArray1 = array1.reshape(2, 3, 2) 
# 2 matrices, 3 rows and 2 columns. 
#Must use this order

print(newArray1)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]


Split arrays

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
# If the array has less elements than required, it will adjust from the end accordingly.
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


Join arrays

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Search Arrays

In [24]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
#the value 4 is present at index 3, 5, and 6

(array([3, 5, 6], dtype=int64),)


In [25]:
#search where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0) #Find the indexes where the values are even is the number devisiable by 2 and print odd numbers
print(x)
print(arr[x])

(array([1, 3, 5, 7], dtype=int64),)
[2 4 6 8]


In [26]:
#seach where the values are odd
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)#Find the indexes where the values are odd is the number devisiable by 2 and print even numbers

print(x)
print(arr[x])

(array([0, 2, 4, 6], dtype=int64),)
[1 3 5 7]


Sorting Arrays

In [27]:
#Sorting by numbers
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [28]:
#sorting alphabetically 
arr = np.array(['blue', 'yellow', 'red'])
print(np.sort(arr))

['blue' 'red' 'yellow']


Mathematics

In [29]:
array = np.arange(0,5)

print(array)

print("Subtract :",array - 10)
print("Multiply :", array * 10)
print("Divide :", array / 10)
print("Power :", array ** 2)

[0 1 2 3 4]
Subtract : [-10  -9  -8  -7  -6]
Multiply : [ 0 10 20 30 40]
Divide : [0.  0.1 0.2 0.3 0.4]
Power : [ 0  1  4  9 16]


NP Dot

In [38]:
#Matrix multiplication
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)

print(c)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [41]:
#Matrix multiplication using matmul
d=np.matmul(a,b)
print(d)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [ ]:
#Columns of first matrix need to be equal to the rows of the second matrix
#This is an example of linear algebra!
a = np.arange(1,7).reshape(3,2)
b = np.arange(7,13).reshape(2,3)
np.matmul(a,b)

NP Sum

In [45]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)
print(c)

total_sum = np.sum(c)
print(total_sum)


[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [46]:
# you can use np.sum on any matrix.
print(a)
sum1 = np.sum(a)
print(sum1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [47]:
#by column
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)

print(c)

e = np.sum(c, axis = 0)

print(e)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[603 648 693]


In [48]:
#by row
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)

print(c)

e = np.sum(c,axis = 1)

print(e)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 270  648 1026]


Mean, Median & Mode

In [52]:
#Mean
height = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = np.mean(height)

print(x)

89.76923076923077


In [53]:
#Median
height = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = np.median(height)

print(x)

87.0


In [54]:
#Mode - NumPy has no attribute called Mode we need to use the Scipy Libray
from scipy import stats as st

height = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = st.mode(height)

print(x)

ModeResult(mode=array([86]), count=array([3]))


C:\Users\GeorginaStanley\AppData\Local\Temp\ipykernel_27808\576382453.py:6: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  x = st.mode(height)


In [56]:
height = [86,87,88,86,87,85,86]

x = np.std(height)
y = np.mean(height)

print ("The STD is:", x)
print("The mean is:", y)

The STD is: 0.9035079029052513
The mean is: 86.42857142857143
